### PR TITLE
Fixed Bison compiler error

### PR DESCRIPTION
**Pull request by madduci**
Added flex_installer in the requirements

Bison 3.4.x requires the `flex` tool during the make process (it is used to build examples in the source code - see https://savannah.gnu.org/forum/forum.php?forum_id=9433)

### CODE REVIEW

**Comment by Croydon** [comment]
The 3.4.1 branch needs a rebase on the 3.3.2 branch first

**Comment by madduci** [comment]
ok, I've worked directly on that branch assuming that it was already done.

**Comment by Croydon** [comment]
@madduci Is flex_installer required for bison or bison_installer?

**Comment by madduci** [comment]
actually for both. Flex is used to generate some sources needed to both targets

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

**Pull request closed without merging**
