### PR TITLE
#348 Add New compilers on CI

### PR DESCRIPTION
**Pull request by uilianries**
- Add GCC 8
- Add clang-apple 9.1
- Add Clang 5,6

close https://github.com/bincrafters/community/issues/348

### CODE REVIEW

**Comment by SSE4** [comment]
one more weirdness
```/bin/sh: line 1: 27930 Illegal instruction: 4  src/bison --version > doc/bison.help.tmp```

**Comment by helmesjo** [comment]
[What is the “Illegal Instruction: 4” error and why does “-mmacosx-version-min=10.x” fix it?](https://stackoverflow.com/a/14285922/2349761)

> "The compiler and linker are capable of using features and performing optimizations that do not work on older OS versions. -mmacosx-version-min tells the tools what OS versions you need to work with, so the tools can disable optimizations that won't run on those OS versions. If you need to run on older OS versions then you must use this flag.
> 
> "The downside to -mmacosx-version-min is that the app's performance may be worse on newer OS versions then it could have been if it did not need to be backwards-compatible. In most cases the differences are small."

**Comment by helmesjo** [comment]
Have you had any time to look into this?

Thanks in advance!

**Comment by SSE4** [comment]
ping @uilianries

**Comment by uilianries** [comment]
I'll check this one later. Thanks!

**Comment by helmesjo** [comment]
@uilianries Have you had any chance to look at this? :)

Sorry for nagging!

**Comment by SSE4** [comment]
@uilianries sound like we have to patch it:
https://github.com/Homebrew/homebrew-core/issues/18591
https://raw.githubusercontent.com/macports/macports-ports/b76d1e48dac/editors/nano/files/secure_snprintf.patch

**Comment by uilianries** [comment]
@SSE4  Awesome! I'll try this! thank you!

**Comment by uilianries** [comment]
@SSE4 Worked like a charm! Thank you!

**Review by SSE4 — APPROVED** [review]
LGTM

**Pull request merged**
